// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4226.BettyLou2019_Command.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4226.BettyLou2019_Command.Robot;

/**
 *
 */
public class Elevator_To_Setpoint extends Command {

    private double m_setpoint = 0.0;
   
    public Elevator_To_Setpoint(double setpoint) {
        requires(Robot.elevator);
        m_setpoint = setpoint;

  
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.elevator.my_Elevator_MotionMagic(m_setpoint);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.elevator.my_Elevator_stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
